---
title: "p8105_hw3_zj2357"
author: "Zekai Jin (zj2357)"
date: "2022-10-10"
output: github_document
---

First of all, we should include the libraries we are using.
```{r init, message=FALSE}
library(tidyverse)
library(p8105.datasets)
library(lubridate)
library(patchwork)
library(forcats)
library(ggridges)
```

# Problem 1

```{r}
data("instacart")
aisle_group = 
  instacart %>%
  group_by(aisle) %>%
  summarise(n_obs =  n()) %>%
  arrange(-n_obs)
```



Thus, there are `r length(aisle_group$aisle)` different aisles. The most popular aisle is `r aisle_group$aisle[1]`.
Then, we make a plot of aisles with more than 10000 items ordered.

```{r, message=FALSE}
aisle_group %>%
  mutate(aisle=fct_reorder(aisle,-n_obs)) %>%
  filter(n_obs > 10000) %>%
  ggplot(aes(x = n_obs,y = aisle,fill=n_obs)) +
  geom_col(orientation="y") +
  xlab("items_saled") +
  viridis::scale_fill_viridis(trans = "log",
                              name = "Items saled",
                              breaks = c(25000,50000,100000)) 
```
The three most popular items in these isles are
```{r, message=FALSE}
instacart %>%
  filter(aisle %in% c("baking ingredients",
                      "dog food care",
                      "packaged vegetables fruits"
                      )
         ) %>%
  group_by(aisle, product_name) %>%
  summarise(
    n_obs=n()
  ) %>%
  arrange(aisle,-n_obs) %>%
  summarise(
    popular_item = head(product_name,3),
    n = head(n_obs,3),
    rank = head(rank(-n_obs),3)
  )
```


```{r, message=FALSE}
instacart %>%
  filter(product_name == "Pink Lady Apples" |
         product_name == "Coffee Ice Cream"
         ) %>%
  group_by(product_name,order_dow) %>%
  summarise(
    mean_hour = mean(order_hour_of_day)
  ) %>%
  pivot_wider(names_from = "order_dow",
              values_from = "mean_hour",
              names_prefix = "day ")
  
  
  
```





# Problem 2
```{r}
rm(list = ls())
accel_df = read_csv("data/accel_data.csv") %>%
  pivot_longer(
    activity.1:activity.1440,
    names_to = "minute",
    names_prefix = "activity.",
    values_to = "activity"
  ) %>%
  mutate(
    minute = as.integer(minute),
    weekends = day %in% c("Saturday","Sunday")
  )
  
accel_df

```


```{r}
accel_df %>%
  group_by(day_id) %>%
  summarise(total_activity = sum(activity))
```




```{r}
accel_df %>%
  mutate(day_id = as.factor(day_id),
         week = as.factor(week),
         day = factor(day,levels = c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday")),
         hour = minute/60) %>%
  group_by(day_id) %>%
  ggplot(aes(x = hour, y = activity, group = day_id, color = day)) +
  geom_smooth(se = FALSE,method = "loess",span=0.4 ) +
  scale_x_continuous(breaks=0:12*2) 



```
  

# Problem 3

```{r}
rm(list = ls())
data("ny_noaa")
ny_noaa = ny_noaa %>%
  mutate(
    id = as.factor(id),
    year = year(date),
    month = factor(month.name[month(date,label=TRUE)],levels=month.name),
    day = day(date),
    prcp = as.double(prcp)/10,
    tmax = as.double(tmax)/10,
    tmin = as.double(tmin)/10
    ) %>%
  select(id,date,year,month,day,everything()) %>%
  arrange(date)

ny_noaa %>%
  group_by(snow) %>%
  summarise(n_obs = n()) %>%
  arrange(-n_obs) %>%
  head(3)
```


```{r}
ny_noaa %>%
  subset(month %in% c("January","July")) %>%
  group_by(year,month,id) %>%
  summarise(
    ave_tmax = mean(tmax,na.rm=TRUE),
  ) %>%
  ggplot() +
  geom_line(aes(x=year,y=ave_tmax,group = id,color = month),alpha = 0.5) +
  facet_grid(~month) +
  theme(legend.position = "none") 


```


```{r}

  ny_noaa %>%
  mutate(day_of_year=yday(date),
         year = as.factor(year)) %>%
  ggplot() +
  geom_smooth(aes(x=day_of_year,y=tmax,color=year))

ny_noaa %>%
  mutate(day_of_year=yday(date),
         year = as.factor(year)) %>%
  group_by(year,day_of_year) %>%
  summarise(ave_tmax = mean(tmax, na.rm = TRUE),
            ave_tmin = mean(tmin, na.rm = TRUE))%>%
  pivot_longer(ave_tmax:ave_tmin,
               names_to = "t_type",
               values_to = "tempreture",
               names_prefix = "ave_") %>%
  ggplot(aes(x=day_of_year, y= tempreture , group = year, color = t_type)) +
  geom_line(alpha = 0.3) +
  facet_grid(~t_type)
  
```





```{r}

ny_noaa %>%
  filter(snow > 0 & snow < 100) %>%
  mutate(year = as.factor(year)) %>%
  ggplot(aes(x=snow,y=year,fill = year)) +
  geom_density_ridges(scale=1.5,alpha=0.5,color="#0000005F") +
  scale_x_continuous(limit = c(0,100))


```







